// Crafting and smelting tables.

import { BLOCKS, ITEMS } from "./constants.js";
export const HAND_RECIPES = [
  {
    id: "planks",
    output: BLOCKS.planks,
    count: 4,
    pattern: [
      [BLOCKS.wood, null],
      [null, null],
    ],
    ingredients: { [BLOCKS.wood]: 1 },
    description: "Saw a log into planks.",
  },
  {
    id: "pine_planks",
    output: BLOCKS.planks,
    count: 4,
    pattern: [
      [BLOCKS.pine_wood, null],
      [null, null],
    ],
    ingredients: { [BLOCKS.pine_wood]: 1 },
    description: "Saw a pine log into planks.",
  },
  {
    id: "torch",
    output: BLOCKS.torch,
    count: 4,
    pattern: [
      [ITEMS.coal, null],
      [ITEMS.stick, null],
    ],
    ingredients: { [ITEMS.coal]: 1, [ITEMS.stick]: 1 },
    description: "Light for the dark places.",
  },
  {
    id: "sticks",
    output: ITEMS.stick,
    count: 4,
    pattern: [
      [BLOCKS.planks, null],
      [BLOCKS.planks, null],
    ],
    ingredients: { [BLOCKS.planks]: 2 },
    description: "Shape planks into sticks.",
  },
];

export const TABLE_RECIPES = [
  {
    id: "crafting_table",
    output: BLOCKS.crafting_table,
    count: 1,
    pattern: [
      [BLOCKS.planks, BLOCKS.planks, null],
      [BLOCKS.planks, BLOCKS.planks, null],
      [null, null, null],
    ],
    ingredients: { [BLOCKS.planks]: 4 },
    description: "Unlock bigger recipes.",
  },
  {
    id: "furnace",
    output: BLOCKS.furnace,
    count: 1,
    pattern: [
      [BLOCKS.stone, BLOCKS.stone, BLOCKS.stone],
      [BLOCKS.stone, null, BLOCKS.stone],
      [BLOCKS.stone, BLOCKS.stone, BLOCKS.stone],
    ],
    ingredients: { [BLOCKS.stone]: 8 },
    description: "Smelt sand and ore.",
  },
  {
    id: "wood_pickaxe",
    output: ITEMS.wood_pickaxe,
    count: 1,
    pattern: [
      [BLOCKS.planks, BLOCKS.planks, BLOCKS.planks],
      [null, ITEMS.stick, null],
      [null, ITEMS.stick, null],
    ],
    ingredients: { [BLOCKS.planks]: 3, [ITEMS.stick]: 2 },
    description: "Break stone and coal ore faster.",
  },
  {
    id: "stone_pickaxe",
    output: ITEMS.stone_pickaxe,
    count: 1,
    pattern: [
      [BLOCKS.stone, BLOCKS.stone, BLOCKS.stone],
      [null, ITEMS.stick, null],
      [null, ITEMS.stick, null],
    ],
    ingredients: { [BLOCKS.stone]: 3, [ITEMS.stick]: 2 },
    description: "Mine iron ore and tougher blocks.",
  },
  {
    id: "bricks",
    output: BLOCKS.bricks,
    count: 4,
    pattern: [
      [BLOCKS.stone, BLOCKS.stone, null],
      [BLOCKS.sand, BLOCKS.sand, null],
      [null, null, null],
    ],
    ingredients: { [BLOCKS.stone]: 2, [BLOCKS.sand]: 2 },
    description: "Decorative masonry block.",
  },
  {
    id: "iron_pickaxe",
    output: ITEMS.iron_pickaxe,
    count: 1,
    pattern: [
      [ITEMS.iron_ingot, ITEMS.iron_ingot, ITEMS.iron_ingot],
      [null, ITEMS.stick, null],
      [null, ITEMS.stick, null],
    ],
    ingredients: { [ITEMS.iron_ingot]: 3, [ITEMS.stick]: 2 },
    description: "Forge a sturdier pickaxe.",
  },
  {
    id: "diamond_pickaxe",
    output: ITEMS.diamond_pickaxe,
    count: 1,
    pattern: [
      [ITEMS.diamond, ITEMS.diamond, ITEMS.diamond],
      [null, ITEMS.stick, null],
      [null, ITEMS.stick, null],
    ],
    ingredients: { [ITEMS.diamond]: 3, [ITEMS.stick]: 2 },
    description: "Cut a pickaxe from diamonds.",
  },
  {
    id: "netherite_pickaxe",
    output: ITEMS.netherite_pickaxe,
    count: 1,
    pattern: [
      [ITEMS.netherite_ingot, ITEMS.diamond_pickaxe, null],
      [null, null, null],
      [null, null, null],
    ],
    ingredients: { [ITEMS.netherite_ingot]: 1, [ITEMS.diamond_pickaxe]: 1 },
    description: "Upgrade a diamond pickaxe with netherite.",
  },
  {
    id: "netherite_ingot",
    output: ITEMS.netherite_ingot,
    count: 1,
    pattern: [
      [ITEMS.netherite_scrap, ITEMS.netherite_scrap, null],
      [ITEMS.netherite_scrap, ITEMS.netherite_scrap, null],
      [null, null, null],
    ],
    ingredients: { [ITEMS.netherite_scrap]: 4 },
    description: "Fuse scrap into an ingot.",
  },
  {
    id: "iron_helmet",
    output: ITEMS.iron_helmet,
    count: 1,
    pattern: [
      [ITEMS.iron_ingot, ITEMS.iron_ingot, ITEMS.iron_ingot],
      [ITEMS.iron_ingot, null, ITEMS.iron_ingot],
      [null, null, null],
    ],
    ingredients: { [ITEMS.iron_ingot]: 5 },
    description: "Iron helmet for protection.",
  },
  {
    id: "iron_chestplate",
    output: ITEMS.iron_chestplate,
    count: 1,
    pattern: [
      [ITEMS.iron_ingot, null, ITEMS.iron_ingot],
      [ITEMS.iron_ingot, ITEMS.iron_ingot, ITEMS.iron_ingot],
      [ITEMS.iron_ingot, ITEMS.iron_ingot, ITEMS.iron_ingot],
    ],
    ingredients: { [ITEMS.iron_ingot]: 8 },
    description: "Iron chestplate for protection.",
  },
  {
    id: "iron_leggings",
    output: ITEMS.iron_leggings,
    count: 1,
    pattern: [
      [ITEMS.iron_ingot, ITEMS.iron_ingot, ITEMS.iron_ingot],
      [ITEMS.iron_ingot, null, ITEMS.iron_ingot],
      [ITEMS.iron_ingot, null, ITEMS.iron_ingot],
    ],
    ingredients: { [ITEMS.iron_ingot]: 7 },
    description: "Iron leggings for protection.",
  },
  {
    id: "iron_boots",
    output: ITEMS.iron_boots,
    count: 1,
    pattern: [
      [ITEMS.iron_ingot, null, ITEMS.iron_ingot],
      [ITEMS.iron_ingot, null, ITEMS.iron_ingot],
      [null, null, null],
    ],
    ingredients: { [ITEMS.iron_ingot]: 4 },
    description: "Iron boots for protection.",
  },
  {
    id: "diamond_helmet",
    output: ITEMS.diamond_helmet,
    count: 1,
    pattern: [
      [ITEMS.diamond, ITEMS.diamond, ITEMS.diamond],
      [ITEMS.diamond, null, ITEMS.diamond],
      [null, null, null],
    ],
    ingredients: { [ITEMS.diamond]: 5 },
    description: "Diamond helmet for protection.",
  },
  {
    id: "diamond_chestplate",
    output: ITEMS.diamond_chestplate,
    count: 1,
    pattern: [
      [ITEMS.diamond, null, ITEMS.diamond],
      [ITEMS.diamond, ITEMS.diamond, ITEMS.diamond],
      [ITEMS.diamond, ITEMS.diamond, ITEMS.diamond],
    ],
    ingredients: { [ITEMS.diamond]: 8 },
    description: "Diamond chestplate for protection.",
  },
  {
    id: "diamond_leggings",
    output: ITEMS.diamond_leggings,
    count: 1,
    pattern: [
      [ITEMS.diamond, ITEMS.diamond, ITEMS.diamond],
      [ITEMS.diamond, null, ITEMS.diamond],
      [ITEMS.diamond, null, ITEMS.diamond],
    ],
    ingredients: { [ITEMS.diamond]: 7 },
    description: "Diamond leggings for protection.",
  },
  {
    id: "diamond_boots",
    output: ITEMS.diamond_boots,
    count: 1,
    pattern: [
      [ITEMS.diamond, null, ITEMS.diamond],
      [ITEMS.diamond, null, ITEMS.diamond],
      [null, null, null],
    ],
    ingredients: { [ITEMS.diamond]: 4 },
    description: "Diamond boots for protection.",
  },
  {
    id: "netherite_helmet",
    output: ITEMS.netherite_helmet,
    count: 1,
    pattern: [
      [ITEMS.netherite_ingot, ITEMS.netherite_ingot, ITEMS.netherite_ingot],
      [ITEMS.netherite_ingot, null, ITEMS.netherite_ingot],
      [null, null, null],
    ],
    ingredients: { [ITEMS.netherite_ingot]: 5 },
    description: "Netherite helmet for protection.",
  },
  {
    id: "netherite_chestplate",
    output: ITEMS.netherite_chestplate,
    count: 1,
    pattern: [
      [ITEMS.netherite_ingot, null, ITEMS.netherite_ingot],
      [ITEMS.netherite_ingot, ITEMS.netherite_ingot, ITEMS.netherite_ingot],
      [ITEMS.netherite_ingot, ITEMS.netherite_ingot, ITEMS.netherite_ingot],
    ],
    ingredients: { [ITEMS.netherite_ingot]: 8 },
    description: "Netherite chestplate for protection.",
  },
  {
    id: "netherite_leggings",
    output: ITEMS.netherite_leggings,
    count: 1,
    pattern: [
      [ITEMS.netherite_ingot, ITEMS.netherite_ingot, ITEMS.netherite_ingot],
      [ITEMS.netherite_ingot, null, ITEMS.netherite_ingot],
      [ITEMS.netherite_ingot, null, ITEMS.netherite_ingot],
    ],
    ingredients: { [ITEMS.netherite_ingot]: 7 },
    description: "Netherite leggings for protection.",
  },
  {
    id: "netherite_boots",
    output: ITEMS.netherite_boots,
    count: 1,
    pattern: [
      [ITEMS.netherite_ingot, null, ITEMS.netherite_ingot],
      [ITEMS.netherite_ingot, null, ITEMS.netherite_ingot],
      [null, null, null],
    ],
    ingredients: { [ITEMS.netherite_ingot]: 4 },
    description: "Netherite boots for protection.",
  },
  {
    id: "chest",
    output: BLOCKS.chest,
    count: 1,
    pattern: [
      [BLOCKS.planks, BLOCKS.planks, BLOCKS.planks],
      [BLOCKS.planks, null, BLOCKS.planks],
      [BLOCKS.planks, BLOCKS.planks, BLOCKS.planks],
    ],
    ingredients: { [BLOCKS.planks]: 8 },
    description: "Somewhere to keep your things.",
  },
  {
    id: "enchanting_table",
    output: BLOCKS.enchanting_table,
    count: 1,
    pattern: [
      [null, ITEMS.diamond, null],
      [ITEMS.diamond, BLOCKS.bricks, ITEMS.diamond],
      [BLOCKS.bricks, BLOCKS.bricks, BLOCKS.bricks],
    ],
    ingredients: { [ITEMS.diamond]: 3, [BLOCKS.bricks]: 4 },
    description: "Build a table to enchant your gear.",
  },
  {
    id: "portal_frame",
    output: BLOCKS.portal_frame,
    count: 6,
    pattern: [
      [BLOCKS.stone, BLOCKS.stone, BLOCKS.stone],
      [BLOCKS.stone, ITEMS.iron_ingot, BLOCKS.stone],
      [BLOCKS.stone, BLOCKS.stone, BLOCKS.stone],
    ],
    ingredients: { [BLOCKS.stone]: 8, [ITEMS.iron_ingot]: 1 },
    description: "Frame blocks for a portal. Ten builds the smallest one.",
  },
  {
    id: "tnt",
    output: BLOCKS.tnt,
    count: 2,
    pattern: [
      [ITEMS.coal, BLOCKS.sand, ITEMS.coal],
      [BLOCKS.sand, ITEMS.coal, BLOCKS.sand],
      [ITEMS.coal, BLOCKS.sand, ITEMS.coal],
    ],
    ingredients: { [ITEMS.coal]: 5, [BLOCKS.sand]: 4 },
    description: "Blows a hole in the scenery. Harmless to people.",
  },
  {
    id: "super_tnt",
    output: BLOCKS.super_tnt,
    count: 1,
    pattern: [
      [null, BLOCKS.tnt, null],
      [BLOCKS.tnt, ITEMS.coal, BLOCKS.tnt],
      [null, BLOCKS.tnt, null],
    ],
    ingredients: { [BLOCKS.tnt]: 4, [ITEMS.coal]: 1 },
    description: "Four charges in one. Twice the reach, still harmless.",
  },
  {
    id: "fire_tnt",
    output: BLOCKS.fire_tnt,
    count: 2,
    pattern: [
      [null, BLOCKS.glowstone, null],
      [BLOCKS.glowstone, BLOCKS.tnt, BLOCKS.glowstone],
      [null, BLOCKS.glowstone, null],
    ],
    ingredients: { [BLOCKS.tnt]: 1, [BLOCKS.glowstone]: 4 },
    description: "Burns off trees and grass, fuses sand to glass, spares stone.",
  },
  {
    id: "car",
    output: ITEMS.car,
    count: 1,
    pattern: [
      [null, ITEMS.iron_ingot, null],
      [ITEMS.iron_ingot, ITEMS.iron_ingot, ITEMS.iron_ingot],
      [ITEMS.coal, null, ITEMS.coal],
    ],
    ingredients: { [ITEMS.iron_ingot]: 4, [ITEMS.coal]: 2 },
    description: "Drive it. Right-click to get in, shift to get out, right-click again to honk.",
  },
  {
    id: "truck",
    output: ITEMS.truck,
    count: 1,
    pattern: [
      [ITEMS.coal, null, ITEMS.coal],
      [null, ITEMS.car, null],
      [ITEMS.coal, null, ITEMS.coal],
    ],
    ingredients: { [ITEMS.car]: 1, [ITEMS.coal]: 4 },
    description: "Four big tyres on a car. Climbs two blocks, and jumps.",
  },
  {
    id: "rig",
    output: ITEMS.rig,
    count: 1,
    pattern: [
      [ITEMS.iron_ingot, ITEMS.iron_ingot, ITEMS.iron_ingot],
      [ITEMS.truck, BLOCKS.planks, BLOCKS.planks],
    ],
    ingredients: { [ITEMS.truck]: 1, [ITEMS.iron_ingot]: 3, [BLOCKS.planks]: 2 },
    description: "A cab and a trailer on monster tyres. Long, slow, and it bends.",
  },
  {
    id: "super_duper_tnt",
    output: BLOCKS.super_duper_tnt,
    count: 1,
    pattern: [
      [null, BLOCKS.super_tnt, null],
      [BLOCKS.super_tnt, ITEMS.netherite_ingot, BLOCKS.super_tnt],
      [null, BLOCKS.super_tnt, null],
    ],
    ingredients: { [BLOCKS.super_tnt]: 4, [ITEMS.netherite_ingot]: 1 },
    description: "The big one. Six seconds of fuse, and you will want them.",
  },
  {
    id: "flood_tnt",
    output: BLOCKS.flood_tnt,
    count: 2,
    pattern: [
      [null, BLOCKS.ice, null],
      [BLOCKS.ice, BLOCKS.tnt, BLOCKS.ice],
      [null, BLOCKS.ice, null],
    ],
    ingredients: { [BLOCKS.tnt]: 1, [BLOCKS.ice]: 4 },
    description: "Washes out a crater and leaves a lake behind.",
  },
  {
    id: "tornado_tnt",
    output: BLOCKS.tornado_tnt,
    count: 2,
    pattern: [
      [null, BLOCKS.leaves, null],
      [BLOCKS.leaves, BLOCKS.tnt, BLOCKS.leaves],
      [null, BLOCKS.leaves, null],
    ],
    ingredients: { [BLOCKS.tnt]: 1, [BLOCKS.leaves]: 4 },
    description: "Rips up a tall column of loose things. Masonry stands.",
  },
  {
    id: "quake_tnt",
    output: BLOCKS.quake_tnt,
    count: 2,
    pattern: [
      [null, BLOCKS.stone, null],
      [BLOCKS.stone, BLOCKS.tnt, BLOCKS.stone],
      [null, BLOCKS.stone, null],
    ],
    ingredients: { [BLOCKS.tnt]: 1, [BLOCKS.stone]: 4 },
    description: "Churns a wide patch of ground into cracked rock.",
  },
  {
    id: "blizzard_tnt",
    output: BLOCKS.blizzard_tnt,
    count: 2,
    pattern: [
      [null, BLOCKS.snow, null],
      [BLOCKS.snow, BLOCKS.tnt, BLOCKS.snow],
      [null, BLOCKS.snow, null],
    ],
    ingredients: { [BLOCKS.tnt]: 1, [BLOCKS.snow]: 4 },
    description: "Freezes water solid and lays snow over everything.",
  },
];

export const FURNACE_RECIPES = [
  {
    id: "glass",
    output: BLOCKS.glass,
    count: 2,
    input: BLOCKS.sand,
    fuel: ITEMS.coal,
    fuelCount: 1,
    inputCount: 2,
    description: "Smelt sand into glass.",
  },
  {
    id: "iron_ingot",
    output: ITEMS.iron_ingot,
    count: 1,
    input: BLOCKS.iron_ore,
    fuel: ITEMS.coal,
    fuelCount: 1,
    inputCount: 1,
    description: "Refine iron ore into ingots.",
  },
  {
    id: "netherite_scrap",
    output: ITEMS.netherite_scrap,
    count: 1,
    input: BLOCKS.ancient_debris,
    fuel: ITEMS.coal,
    fuelCount: 1,
    inputCount: 1,
    description: "Cook debris down to scrap.",
  },
];
