// The single mutable game state object.

import { BLOCKS, DEFAULT_SPAWN, ITEMS } from "./constants.js";
export const state = {
  mode: "menu",
  screen: "title",
  screenReturn: "title",
  gameMode: "survival",
  running: false,
  isDead: false,
  lastSafePosX: DEFAULT_SPAWN.x,
  lastSafePosZ: DEFAULT_SPAWN.z,
  pointerLocked: false,
  intentionalUnlock: false,
  pointerLockUnavailable: false,
  suppressInteractUntil: 0,
  suppressAnimationTick: false,
  inventoryOpen: false,
  saveDirty: false,
  saveCooldown: 0,
  keys: new Set(),
  awaitingBind: null,
  selectedBlock: BLOCKS.grass,
  activeSlot: 0,
  hotbarSlots: [
    ITEMS.wood_pickaxe,
    BLOCKS.grass,
    BLOCKS.dirt,
    BLOCKS.stone,
    BLOCKS.wood,
    BLOCKS.sand,
    BLOCKS.planks,
    BLOCKS.crafting_table,
    BLOCKS.furnace,
  ],
  lastInteractionTime: 0,
  elapsed: 0,
  target: null,
  dragLook: false,
  dragAnchor: null,
  dayTime: 0.34,
  uiMessage: "",
  uiMessageTimer: 0,
  heldItemTimer: 0,
  heldItemName: "",
  viewBob: 0,
  stepPhase: 0,
  landingBounce: 0,
  nextFootstepAt: 0,
  sneaking: false,
  sprinting: false,
  sprintLatched: false,
  lastForwardTapTime: -99,
  lastJumpTapTime: -99,
  flying: false,
  flyVelocityY: 0,
  perspective: 0,
  hudVisible: true,
  screenshotRequested: false,
  debugVisible: false,
  frameTimes: [],
  fps: 0,
  panoramaAngle: 0,
  safeAnchorCooldown: 0,
  drops: [],
  breakState: {
    key: null,
    blockType: BLOCKS.air,
    progress: 0,
    hardness: 1,
    lastHitTime: -999,
    pulse: 0,
  },
  inventory: {
    [BLOCKS.grass]: 20,
    [BLOCKS.dirt]: 18,
    [BLOCKS.stone]: 24,
    [BLOCKS.wood]: 10,
    [BLOCKS.pine_wood]: 0,
    [BLOCKS.planks]: 0,
    [BLOCKS.sand]: 16,
    [BLOCKS.bricks]: 0,
    [BLOCKS.glass]: 0,
    [BLOCKS.snow]: 0,
    [BLOCKS.ice]: 0,
    [BLOCKS.crafting_table]: 0,
    [BLOCKS.furnace]: 0,
    [BLOCKS.coal_ore]: 0,
    [BLOCKS.iron_ore]: 0,
    [ITEMS.stick]: 0,
    [ITEMS.coal]: 0,
    [ITEMS.iron_ingot]: 0,
    [ITEMS.wood_pickaxe]: 1,
    [ITEMS.stone_pickaxe]: 0,
  },
  player: {
    x: DEFAULT_SPAWN.x,
    // Real spawn height needs the world, so main.js sets this during boot.
    y: 0,
    z: DEFAULT_SPAWN.z,
    vx: 0,
    vy: 0,
    vz: 0,
    yaw: DEFAULT_SPAWN.yaw,
    pitch: DEFAULT_SPAWN.pitch,
    onGround: false,
  },
};
